# Generated by Django 5.1.4 on 2024-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.AddField(
            model_name="profile",
            name="country_code",
            field=models.CharField(default="IN", max_length=5),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="N/A", max_length=255),
        ),
    ]
